ALTER DATABASE Customer -- old Database Name
SET SINGLE_USER WITH ROLLBACK IMMEDIATE
--GO
ALTER DATABASE Customer --old Database Name
MODIFY NAME = Joel --New Name
ALTER DATABASE Joel -- New Name
SET MULTI_USER WITH ROLLBACK IMMEDIATE
--GO